name: docs-dev

on:
  push:
    branches:
      - dev

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  docs:
    runs-on: runner-gr-lora_sdr

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/dev-docs/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/dev-docs/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Make documentation
        working-directory: ${{runner.workspace}}/dev-docs/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
        #run : make doc

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: "gh-pages"

      - name: Move gh-pages
        working-directory: ${{runner.workspace}}
        #move to folder up for easy use
        run: |
          mv gr-lora_sdr/gh-pages/ .
        ##rm -rf gr-lora_sdr/gh-pages/

      - name: Add new exported documentation and push to gh-pages branch
        working-directory: ${{runner.workspace}}
        run: |
          cp -r ${{runner.workspace}}/dev-docs/build/docs/doxygen/html ${{runner.workspace}}/gh-pages/
          cd ${{runner.workspace}}/gh-pages/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatically updated the wiki" && git push
          cd ../ && rm -rf gh-pages

      - name: Remove build dir
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          rm -rf dev-docs
